name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: skyfrk/udhbwvst:4.5.2
      volumes:
        - $GITHUB_WORKSPACE:/work
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Display versions of build tools
        run: |
          latexmk -v
          lualatex --version
          java -jar $PLANTUML_JAR -version
      - name: Build PDF
        run: |
          cd src && latexmk \
            -synctex=1 \
            -interaction=nonstopmode \
            -file-line-error \
            -shell-escape \
            -pdf \
            -pdflatex=lualatex \
            main
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: software_concept
          path: src/main.pdf
      - name: Rename artifact for release
        run: mv src/main.pdf "Animal_Abduction_Crew_Software_Concept_${GITHUB_REF##*/}.pdf"
      - name: Release artifact to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*Animal_Abduction_Crew_Software_Concept*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
